AllCops:
  # Include gemspec and Rakefile
  Include:
    - '**/*.gemspec'
    - '**/*.podspec'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
    - '**/Podfile'
    - '**/Thorfile'
    - '**/Vagrantfile'
  Exclude:
    - 'vendor/**/*'
    - 'stubs/**/*'

Lint/Eval:
  Enabled: false

Metrics/LineLength:
  Max: 110

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 120

Style/RaiseArgs:
  Enabled: false

Style/Documentation:
  Enabled: false
